---

- name: Ensure libreoffice_version is set
  assert:
    that: libreoffice_version|length > 0
    fail_msg: Please set "libreoffice_version"

- name: Add LibreOffice yum repo
  yum_repository:
    name: '{{ libreoffice_repo }}'
    description: LibreOffice Suite
    baseurl: http://yum.library.ucla.edu/libre-{{ libreoffice_version }}
    gpgcheck: false

- name: Generate list of LibreOffice RPMs to be installed
  shell: # noqa: command-instead-of-module
    cmd: yum list --disablerepo=\* --enablerepo={{ libreoffice_repo }} --installroot=/nonexistant -q | sed -ne '/Available Packages/{n}; s/ .*//p'
    warn: false
  changed_when: false
  check_mode: false
  register: libreoffice_rpm_list

- name: Install LibreOffice RPMS
  yum:
    name: "{{ libreoffice_rpm_list.stdout_lines + libreoffice_required_packages }}"
    state: present

- name: Create LibreOffice symblink in user path
  file:
    src: "{{ libreoffice_install_path }}/program/soffice"
    path: "/usr/local/bin/soffice"
    state: link
